export default {
  skills: [
    { name: 'Programmation Full-Stack', category: 'Programmation Web' },
    { name: 'Intelligence Artificielle', category: 'Programmation' },
    { name: 'Machine Learning', category: 'Programmation' },
    { name: 'Flutter', category: 'Programmation' },
    { name: 'React Native', category: 'Programmation' },
    { name: 'Android Studio', category: 'Programmation' },
    { name: 'C', category: 'Programmation' },
    { name: 'C++', category: 'Programmation' },
    { name: 'C#', category: 'Programmation' },
    { name: 'Go', category: 'Programmation' },
    { name: 'Dart', category: 'Programmation' },
    { name: 'Python', category: 'Programmation' },
    { name: 'PHP', category: 'Programmation' },
    { name: 'Java', category: 'Programmation' },
    { name: 'JavaScript', category: 'Programmation' },
    { name: 'TypeScript', category: 'Programmation' },
    { name: 'ReactJs', category: 'Programmation' },
    { name: 'VueJs', category: 'Programmation' },
    { name: 'NodeJs', category: 'Programmation' },
    { name: 'Laravel', category: 'Programmation' },
    { name: 'Symphony', category: 'Programmation' },
    { name: 'Django', category: 'Programmation' },
    { name: 'SpringBoot', category: 'Programmation' },
    { name: 'Scala', category: 'Programmation' },
    { name: 'Cybersécurité', category: 'Administration Réseau' },
    { name: 'Cloud Computing (Azure, AWS)', category: 'DevOps' },
    { name: 'Automatisation (Bash)', category: 'DevOps' },
    { name: 'Docker', category: 'DevOps' },
    { name: 'Kubernetes', category: 'DevOps' },
    { name: 'Blockchain & Web3', category: 'Programmation' },
    { name: 'Solidity', category: 'Programmation' },
    { name: 'SQL', category: 'Programmation' },
    { name: 'noSQL', category: 'Programmation' },
    { name: 'postgresSQL', category: 'Programmation' },

    { name: 'Design Graphique', category: 'Design' },
    { name: 'UI/UX Design (Figma)', category: 'Design' },
    { name: 'Motion Design', category: 'Design' },
    { name: 'Illustration', category: 'Design' },
    { name: 'Design Web Responsive', category: 'Design' },
    { name: 'Photographie', category: 'Design' },
    { name: 'Montage Vidéo (Premiere Pro)', category: 'Design' },
    { name: 'Création de Logo', category: 'Design' },
    { name: 'Design Packaging', category: 'Design' },
    { name: 'Modélisation 3D (Blender)', category: 'Design' },

    { name: 'Marketing Numérique', category: 'Marketing' },
    { name: 'SEO & Référencement', category: 'Marketing' },
    { name: 'Publicité en Ligne (Google Ads)', category: 'Marketing' },
    { name: 'Content Marketing', category: 'Marketing' },
    { name: 'Marketing d’Influence', category: 'Marketing' },
    { name: 'Email Marketing (Mailchimp)', category: 'Marketing' },
    { name: 'Google Analytics', category: 'Marketing' },
    { name: 'Stratégie Marketing', category: 'Marketing' },
    { name: 'CRM (Salesforce)', category: 'Marketing' },
    { name: 'Growth Hacking', category: 'Marketing' },

    { name: 'Rédaction Web SEO', category: 'Rédaction' },
    { name: 'Copywriting', category: 'Rédaction' },
    { name: 'Rédaction Technique', category: 'Rédaction' },
    { name: 'Journalisme', category: 'Rédaction' },
    { name: 'Écriture de Livres', category: 'Rédaction' },
    { name: 'Traduction', category: 'Rédaction' },
    { name: 'Correction & Édition', category: 'Rédaction' },
    { name: 'Scripting Vidéo', category: 'Rédaction' },
    { name: 'Storytelling', category: 'Rédaction' },
    { name: 'Rédaction Réseaux Sociaux', category: 'Rédaction' },

    { name: 'Gestion de Projet (Agile, Scrum)', category: 'Gestion' },
    { name: 'Assistance Virtuelle', category: 'Gestion' },
    { name: 'Coaching Carrière', category: 'Gestion' },
    { name: 'Planification Stratégique', category: 'Gestion' },
    { name: 'Gestion d’Équipes Distantes', category: 'Gestion' },
    { name: 'Support Client', category: 'Gestion' },
    { name: 'Formation Professionnelle', category: 'Gestion' },
    { name: 'Optimisation de Processus', category: 'Gestion' },
    { name: 'Gestion Budgétaire', category: 'Gestion' },
    { name: 'Logistique', category: 'Gestion' },

    { name: 'Comptabilité', category: 'Finance' },
    { name: 'Analyse Financière', category: 'Finance' },
    { name: 'Planification Fiscale', category: 'Finance' },
    { name: 'Gestion de Budget', category: 'Finance' },
    { name: 'Audit', category: 'Finance' },
    { name: 'Finance d’Entreprise', category: 'Finance' },
    { name: 'Investissement', category: 'Finance' },
    { name: 'QuickBooks', category: 'Finance' },
    { name: 'Prévision Financière', category: 'Finance' },
    { name: 'Gestion des Risques', category: 'Finance' },

    { name: 'Consulting Stratégique', category: 'Consulting' },
    { name: 'Consulting Management', category: 'Consulting' },
    { name: 'Consulting RH', category: 'Consulting' },
    { name: 'Consulting Innovation', category: 'Consulting' },
    { name: 'Consulting Marketing', category: 'Consulting' },
    { name: 'Transformation Digitale', category: 'Consulting' },
    { name: 'Consulting Durabilité', category: 'Consulting' },
    { name: 'Analyse Concurrentielle', category: 'Consulting' },
    { name: 'Stratégie d’Entreprise', category: 'Consulting' },
    { name: 'Consulting Croissance', category: 'Consulting' },

    { name: 'Excel', category: 'Bureautique' },
    { name: 'Word', category: 'Bureautique' },
    { name: 'PowerPoint', category: 'Bureautique' },
    { name: 'Google Sheets', category: 'Bureautique' },
    { name: 'Google Docs', category: 'Bureautique' },
    { name: 'Google Slides', category: 'Bureautique' },
    { name: 'Création de Présentations', category: 'Bureautique' },
    { name: 'Formulaires Google', category: 'Bureautique' },

    { name: 'Santé Digitale', category: 'Santé' },
    { name: 'eLearning & Formation en Ligne', category: 'Éducation' },
    { name: 'Coaching Nutrition', category: 'Santé' },
    { name: 'Contenu Éducatif', category: 'Éducation' },
    { name: 'Analyse de Données Santé', category: 'Santé' },
    { name: 'Rédaction Médicale', category: 'Santé' },
    { name: 'UX pour Apps Santé', category: 'Santé' },
  ],

  roles: [
    { slug: 'SUPER_ADMIN', title: 'Super Administrateur', scope: 'admin' },
    { slug: 'ADMIN', title: 'Administrateur', scope: 'admin' },
    { slug: 'COMPANY_ADMIN', title: 'Responsable entreprise', scope: 'company' },
    { slug: 'RECRUITER', title: 'Recruteur entreprise', scope: 'company' },
    { slug: 'TALENT', title: 'Talent', scope: 'talent' },
  ],

  permissions: [
    { slug: 'manage_company', title: 'Gérer les paramètres de l’entreprise', scope: 'company' },
    { slug: 'add_member', title: 'Ajouter un membre dans l’entreprise', scope: 'company' },
    { slug: 'remove_member', title: 'Retirer un membre de l’entreprise', scope: 'company' },
    { slug: 'create_job_offer', title: 'Créer une offre d’emploi', scope: 'company' },
    { slug: 'edit_job_offer', title: 'Modifier une offre d’emploi', scope: 'company' },
    { slug: 'delete_job_offer', title: 'Supprimer une offre d’emploi', scope: 'company' },
    { slug: 'view_applications', title: 'Voir les candidatures', scope: 'company' },
    { slug: 'apply_job', title: 'Postuler à une offre', scope: 'talent' },
    { slug: 'view_own_applications', title: 'Voir ses propres candidatures', scope: 'talent' },
    { slug: 'manage_users', title: 'Gérer les utilisateurs', scope: 'admin' },
    { slug: 'manage_roles', title: 'Gérer les rôles et permissions', scope: 'admin' },
    { slug: 'view_dashboard', title: 'Accéder au tableau de bord', scope: 'admin' },
    { slug: 'delete_company', title: 'Supprimer une entreprise', scope: 'admin' },
    { slug: 'restore_user', title: 'Restaurer un utilisateur supprimé', scope: 'admin' },
  ],
}
